name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: poetry run flake8 .
      - name: Lint with black
        run: poetry run black . --check
      - name: Test with pytest
        run: poetry run pytest --junitxml=junit/test-results.xml --cov=meetpi --cov-report=xml --cov-report=html